name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_RELEASE_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          always-auth: true
          registry-url: https://registry.npmjs.org

      - name: Set up Git
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"

      - name: Set up pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8.15

      - name: Install dependencies
        run: pnpm install

      - name: Tests
        run: pnpm test

      - name: Build
        run: pnpm build

      - name: Publish
        if: github.ref == 'refs/heads/main'
        run: pnpm release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_RELEASE_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
