name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_RELEASE_TOKEN }}

      - name: Setup Git
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"

      - name: Install dependencies
        uses: bahmutov/npm-install@v1
        with:
          useLockFile: false

      - name: Test the library
        run: yarn test

      - name: Build the library
        run: yarn build

      - name: Publish
        if: github.ref == 'refs/heads/main'
        run: yarn release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_RELEASE_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
